name: myfirstaction

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing
        run: |
             echo "Hello World"
             echo "Kijiye meeting meeting"
      - name: Completed
        run: echo "Done"
